### ISSUE TITLE
train loss decrease but val loss increase

### ISSUE THREAD

**Issue by henryccl** [daniellerch/stegolab#1]
while I run stego_cnn_xu.py  I ran out of memory, so i use git_generator  but i get a terrible accurate

Epoch 1/10
 - 383s - loss: 0.5388 - acc: 0.7156 - val_loss: 0.7477 - val_acc: 0.5938
Epoch 2/10
 - 377s - loss: 0.4599 - acc: 0.7707 - val_loss: 0.7986 - val_acc: 0.6250
Epoch 3/10
 - 378s - loss: 0.3090 - acc: 0.8372 - val_loss: 1.1656 - val_acc: 0.5312
Epoch 4/10
 - 377s - loss: 0.2499 - acc: 0.8438 - val_loss: 1.3593 - val_acc: 0.5625
Epoch 5/10
 - 378s - loss: 0.2135 - acc: 0.8454 - val_loss: 1.4827 - val_acc: 0.5625

I want to ask did you get the same accurate as Xu ?   Is the way I deal with dataset wrong?

**Comment by daniellerch** [comment]
You are overfitting. May be you are using few images ...
